#!/usr/bin/env zsh

if [ ! -d /usr/local/Cellar ]; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if [ ! -d /usr/local/Library/Taps/homebrew/homebrew-dupes ]; then
  brew tap homebrew/dupes
fi

brew update

for formula in \
  brew-gem \
  curl git gh gnupg2 psgrep pstree pv tree watch wget \
  vim \
  apple-gcc42 automake autoconf \
  mysql \
  postgresql geos postgis geoip \
  elasticsearch \
  redis \
  node \
  ffmpeg \
  rbenv rbenv-default-gems rbenv-communal-gems rbenv-gem-rehash rbenv-vars ruby-build \
  imagemagick json-c libffi libmaxminddb sqlite3 exiv2; do

  if [ ! -d "$(brew --prefix $formula)" ]; then
    brew install $formula
  fi
done

if ! whence -w rbenv | grep -q "rbenv: function"; then
  eval "$(rbenv init -)"
fi

mkdir -p "$(rbenv root)/cache"

for gem in gem-open bundler foreman github-mark{up,down}; do
  if ! grep -q "$gem" "$(rbenv root)/default-gems"; then
    echo "$gem" >> "$(rbenv root)/default-gems"
  fi
done

for version in \
  2.2.2 2.1.6 2.0.0-p645 1.9.3-p551 1.8.7-p375 \
  jruby-1.6.8 jruby-1.7.19 \
  rbx-1.2.4 rbx-2.5.2; do

if [ ! -d "$(rbenv root)/versions/$version" ]; then
    rbenv install $version
  fi

  # jruby doesn't work with communized gems
  if grep -q jruby <<< "$version" && [ -L "$(rbenv root)/versions/$version/lib/ruby/gems" ]; then
    rbenv sequester "$version"
  fi
done

if [ "$(rbenv global)" != "2.2.2" ]; then
  rbenv global 2.2.2
fi
