#!/usr/bin/env zsh

pushd $HOME

  if [ -e $HOME/.home ]; then
    pushd $HOME/.home
      git pull
      git submodule update --init --recursive
    popd
  else
    git clone --recursive ssh://git@github.com/sj26/home.git .home
  fi

  pushd $HOME/.home
    git pull
    git submodule update
  popd

  for file in .ackrc .bin .gemrc .git{config,ignore,attributes} .js .pryrc .railsrc .tmux.conf .vim .zsh
    [ -L $file ] || ln -fs .home/$file
  for suffix in rc
    [ -L .vim$suffix ] || ln -fs .vim/$suffix .vim$suffix
  for suffix in env profile rc
    [ -L .zsh$suffix ] || ln -fs .zsh/$suffix .zsh$suffix

  [ "$(uname -s)" = "Darwin" ] && .home/move-in-osx

popd
