if has('vim_starting')
  execute pathogen#infect()
end

if has('persistent_undo')
  set undofile
  set undodir=$HOME/.vim/undo
endif

colors jellybeans

let mapleader = ','

nmap <Leader>v :e $MYVIMRC<CR>

" Format lists within comments
" https://stackoverflow.com/a/37172060/158252
set formatoptions+=n
set formatlistpat=^\\s*\\w\\+[.\)]\\s\\+\\\\|^\\s*[\\-\\+\\*]\\+\\s\\+

" Remember last location in file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif

" netrw
" <Ctrl-^> should go to the last file, not to netrw.
" https://github.com/tpope/vim-vinegar/issues/25#issuecomment-42727977
let g:netrw_altfile = 1

" fzf
nmap ; :Windows<CR>
nmap <Leader>f :Files<CR>
nmap <Leader>t :Tags<CR>

" rails
if !exists('g:rails_projections')
  let g:rails_projections = {}
endif
call extend(g:rails_projections, {
      \  "app/presenters/*.rb": {
      \     "command": "presenter",
      \     "test": "spec/presenter/{}_spec.rb",
      \     "alternate": "spec/presenter/{}_spec.rb",
      \     "template": "class {camelcase|capitalize|colons}\nend" }
      \ }, 'keep')
if !exists('g:rails_gem_projections')
  let g:rails_gem_projections = {}
endif
call extend(g:rails_gem_projections, {
      \ "rspec": {
      \    "spec/support/*.rb": {
      \      "command": "support"}},
      \ }, 'keep')
